Remove unwanted links from header.
ThinkOpenly/RISC-V_ISA pull request #18
Opened 2024-08-19 08:33 UTC by Linda-Njau

Remove the `href` attribute from `HeaderName`.
Replace the vertical bar  wrapped in `HeaderMenuItem` with a `span` elemnent and apply styling.

2024-08-20 20:42 UTC, ThinkOpenly requested changes
Minor changes to the commit message only:
> Remove unwanted links from header.

remove the trailing period '.'.

> Remove the `href` attribute from `HeaderName`.

add the "why".

> Replace the vertical bar  wrapped in `HeaderMenuItem` with a `span` elemnent and apply styling.

extra space between "bar  wrapped".
fix spelling of "element".

2024-08-21 13:01 UTC, Linda-Njau commented
Fixed : )

2024-08-21 13:52 UTC, ThinkOpenly commented
> > > Replace the vertical bar  wrapped in `HeaderMenuItem` with a `span` elemnent and apply styling.
> > 
> > extra space between "bar wrapped". fix spelling of "element".
> 
> Fixed : )

I still see an extra space there, but who's counting. I'll let the CI Action complete and then merge.

2024-08-21 13:53 UTC, ThinkOpenly approved these changes

2024-08-27 19:43 UTC, merged